[build]
  publish = "dist"
  command = "npm run build"

# Force HTTPS and www to non-www in a single rule
[[redirects]]
  from = "http://*"
  to = "https://elegantlashesbykatie.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.elegantlashesbykatie.com/*"
  to = "https://elegantlashesbykatie.com/:splat"
  status = 301
  force = true

# Redirect temporary domain
[[redirects]]
  from = "https://dlu.ano.mybluehost.me/*"
  to = "https://elegantlashesbykatie.com/:splat"
  status = 301
  force = true

# Blog clean URL redirect
[[redirects]]
  from = "/blog.html"
  to = "/blog"
  status = 301
  force = true

# Headers for all files
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=86400"
    Link = "</css/styles.css>; rel=preload; as=style"

# Headers for static assets
[[headers]]
  for = "*.{jpg,jpeg,png,gif,webp,ico,svg,woff,woff2,ttf,eot}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers for CSS and JS
[[headers]]
  for = "*.{css,js}"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# Headers for HTML files
[[headers]]
  for = "*.{html,htm}"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"